max_epochs: 50
accelerator: gpu
devices: [0]
precision: 16-mixed
learning_rate: 0.001

logger:
  dir: logs
  name: swinunet_fire_predictor

callbacks:
  early_stopper:
    enabled: true
    monitor: val_loss
    patience: 5
    mode: min
    min_delta: 0.01
  image_logger:
    enabled: true

